### ISSUE TITLE
使用tidevice执行Fastbot iOS, 支持Windows上执行

### ISSUE THREAD

**Issue by jongyu** [bytedance/Fastbot_iOS#1]
- 执行命令(Fastbot的参数使用-e 指定)
```
tidevice xctest -B fastbot的bundle_id -e BUNDLEID:被测应用的bundle_id -e duration:测试时长 -e throttle:300
```
- 实际例子(基于QQ音乐)
```
tidevice xctest -B bytedance.FastbotRunner -e BUNDLEID:com.tencent.QQMusic -e duration:5 --debug
```

**Comment by bluepang** [comment]
问下，throttle不设置，默认是多少？

**Comment by jongyu** [comment]
> 问下，throttle不设置，默认是多少？

这个貌似默认是300(我自己把它改成了100), duration的时间默认是15分钟, duration建议自己设置长一些

**Comment by bluepang** [comment]
> 这个貌似默认是300(我自己把它改成了100), duration的时间默认是15分钟, duration建议自己设置长一些

好的，谢谢

**Comment by bluepang** [comment]
不好意思，请问throttle极限值能达到多少，设置到100感觉压力还是不是很够（相对安卓端的Maxim），跑了6个小时，没发现问题

**Comment by geron-cn** [comment]
> 不好意思，请问throttle极限值能达到多少，设置到100感觉压力还是不是很够（相对安卓端的Maxim），跑了6个小时，没发现问题

你可以尝试下 -200 ～  -100，这是一个极限值了。

**Comment by pingchaodeng** [comment]
你好，请问windows上执行的话，需要配置什么运行环境吗

**Comment by jongyu** [comment]
> 你好，请问windows上执行的话，需要配置什么运行环境吗

去看这个[taobao-iphone-device](https://github.com/alibaba/taobao-iphone-device)

**Comment by pingchaodeng** [comment]
> > 你好，请问windows上执行的话，需要配置什么运行环境吗
> 
> 去看这个[taobao-iphone-device](https://github.com/alibaba/taobao-iphone-device)

好的 多谢

**Comment by bluepang** [comment]
您的邮件我已收到，请您放心！

**Comment by hanhongcat** [comment]
您好，windows上使用tidevice 跑iosmonkey，命令：tidevice xctest -B bytedance.FastbotRunner.xctrunner -e BUNDLEID:com.fdzq.ForthrightSecurities -e duration:960 -e throttle:500 --debug
 实际跑了不到两小时就停止了。报错： dtxm socket closed
 xctrunner quited。请帮忙看下怎么处理

**Comment by bluepang** [comment]
您的邮件我已收到，请您放心！
