### ISSUE TITLE
App crash 之后，一直循环出现网络未连接

### ISSUE THREAD

**Issue by sadmenmen** [bytedance/Fastbot_iOS#10]
执行命令
tidevice xctest -B bytedance.FastbotRunnermenmen.xctrunner -e BUNDLEID:com.xiaomi.mihome.dailybuild -e duration:5 --debug

app crash 之前一切正常，app crash 之后提示如下
命令窗口消息

[D 210804 11:01:09 _instruments:606] Ignore notification from server: 2189, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:30.981371+0800 FastbotRunner-Runner[360:16170] Task <E38EE8AF-3584-43EE-959B-F9B1806DC39F>.<156> HTTP load failed (error code: -1009 [1:50])\n2021-07-07 01:36:30.981845+0800 FastbotRunner-Runner[360:16170] Task <E38EE8AF-3584-43EE-959B-F9B1806DC39F>.<156> finished with error - code: -1009\n', 360, 50461342180])
[D 210804 11:01:09 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:30.982993+0800 FastbotRunner-Runner[360:16170] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x280555aa0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription= 似乎已断开与互联网的连接。}\n', 360, 50461395943])
[D 210804 11:01:09 _device:944] logProcess: 2021-07-07 01:36:30.982993+0800 FastbotRunner-Runner[360:16170] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x280555aa0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=似乎已断开与互联网的连接。}
[D 210804 11:01:09 _instruments:606] Ignore notification from server: 2190, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:30.982993+0800 FastbotRunner-Runner[360:16170] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x280555aa0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=似乎已断开与互联网的连接。}\n', 360, 50461395943])
[D 210804 11:01:09 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:30.984414+0800 FastbotRunner-Runner[360:13910] By tapping FastbotRunner on the device, the screen of the device would go black for about one minute. During the black screen interval, users should press the home button on the device to go back to the main screen. Wait patiently until the network setting dialog window pops up. Users should allow the pop up request in order to continue.\n', 360, 50461417931])
[D 210804 11:01:09 _device:944] logProcess: 2021-07-07 01:36:30.984414+0800 FastbotRunner-Runner[360:13910] By tapping FastbotRunner on the device, the screen of the device would go black for about one minute. During the black screen interval, users should press the home button on the device to go back to the main screen. Wait patiently until the network setting dialog window pops up. Users should allow the pop up request in order to continue.
[D 210804 11:01:09 _instruments:606] Ignore notification from server: 2191, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:30.984414+0800 FastbotRunner-Runner[360:13910] By tapping FastbotRunner on the device, the screen of the device would go black for about one minute. During the black screen interval, users should press the home button on the device to go back to the main screen. Wait patiently until the network setting dialog window pops up. Users should allow the pop up request in order to continue.\n', 360, 50461417931])
[D 210804 11:01:10 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.990096+0800 FastbotRunner-Runner[360:14491] TIC TCP Conn Failed [157:0x283f7f9c0]: 1:50 Err(50)\n', 360, 50485545444])
[D 210804 11:01:10 _device:944] logProcess: 2021-07-07 01:36:31.990096+0800 FastbotRunner-Runner[360:14491] TIC TCP Conn Failed [157:0x283f7f9c0]: 1:50 Err(50)
[D 210804 11:01:10 _instruments:606] Ignore notification from server: 2192, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.990096+0800 FastbotRunner-Runner[360:14491] TIC TCP Conn Failed [157:0x283f7f9c0]: 1:50 Err(50)\n', 360, 50485545444])
[D 210804 11:01:10 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.995081+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> HTTP load failed (error code: -1009 [1:50])\n', 360, 50485664947])
[D 210804 11:01:10 _device:944] logProcess: 2021-07-07 01:36:31.995081+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> HTTP load failed (error code: -1009 [1:50])
[D 210804 11:01:10 _instruments:606] Ignore notification from server: 2193, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.995081+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> HTTP load failed (error code: -1009 [1:50])\n', 360, 50485664947])
[D 210804 11:01:10 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.995464+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> finished with error - code: -1009\n2021-07-07 01:36:31.996000+0800 FastbotRunner-Runner[360:14491] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x28055d860 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=似乎已断开与互联网的连接。}\n', 360, 50485678231])
[D 210804 11:01:10 _device:944] logProcess: 2021-07-07 01:36:31.995464+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> finished with error - code: -1009
    2021-07-07 01:36:31.996000+0800 FastbotRunner-Runner[360:14491] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x28055d860 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=似乎已断开与互联网的连接。}
[D 210804 11:01:10 _instruments:606] Ignore notification from server: 2194, 0x2, ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.995464+0800 FastbotRunner-Runner[360:14491] Task <30591829-C23E-450E-AC2E-B403C7F2F43B>.<157> finished with error - code: -1009\n2021-07-07 01:36:31.996000+0800 FastbotRunner-Runner[360:14491] error Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={NSUnderlyingError=0x28055d860 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://www.bytedance.com/, NSErrorFailingURLKey=http://www.bytedance.com/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=似乎已断开与互联网的连接。}\n', 360, 50485678231])
[D 210804 11:01:10 _instruments:591] DTXMessage: expects_reply:0 flags:2 ('outputReceived:fromProcess:atTime:', ['2021-07-07 01:36:31.996585+0800 FastbotRunner-Runner[360:13910] By tapping FastbotRunner on the device, the screen of the device would go black for about one minute. During the black screen interval, users should press the home button on the device to go back to the main screen. Wait patiently until the network setting dialog window pops up. Users should allow the pop up request in order to continue.\n', 360, 50485701026])
[D 210804 11:01:10 _device:944] logProcess: 2021-07-07 01:36:31.996585+0800 FastbotRunner-Runner[360:13910] By tapping FastbotRunner on the device, the screen of the device would go black for about one minute. During the black screen interval, users should press the home button on the device to go back to the main screen. Wait patiently until the network setting dialog window pops up. Users should allow the pop up request in order to continue.

**Comment by geron-cn** [comment]
大致分析：  未指定 `testFastbot` testcase 运行，则默认运行了两个 testcase，第一个运行结束后，自动切换到 testPingNetwork 这个 case 上去了。

1.   duration 设置 5 分钟太短了， 建议 > 360
2.  需要 `似乎已断开与互联网的连接` 这个首次出现前后的 log ， 确定下是否是因为 被测试 App crash 了， 导致了 case 的切换
3.  指定 `testFastbot` 运行也可以解决这个问题

**Comment by bluepang** [comment]
我也出现过这个问题：tidevice xctest -B .FastbotRunner.xctrunner -e BUNDLEID:xx -e duration:1 --debug

**Comment by geron-cn** [comment]
> 我也出现过这个问题：tidevice xctest -B .FastbotRunner.xctrunner -e BUNDLEID:xx -e duration:1 --debug
> [monkey.log](https://github.com/bytedance/Fastbot_iOS/files/6937083/monkey.log)

看了下你这个 log， 你这个是正常流程， tidevice 会默认执行两个 case， 第一个 testFastbot 执行结束后就会执行 testPingNetwork。

1. 可以延长下 duration，1分钟实在太短了， 建议 >360。
2. 如果不需要的话直接注释掉 testPingNetwork 即可解决这个问题。

**Comment by bluepang** [comment]
> > 我也出现过这个问题：tidevice xctest -B .FastbotRunner.xctrunner -e BUNDLEID:xx -e duration:1 --debug
> > [monkey.log](https://github.com/bytedance/Fastbot_iOS/files/6937083/monkey.log)
> 
> 看了下你这个 log， 你这个是正常流程， tidevice 会默认执行两个 case， 第一个 testFastbot 执行结束后就会执行 testPingNetwork。
> 
> 1. 可以延长下 duration，1分钟实在太短了， 建议 >360。
> 2. 如果不需要的话直接注释掉 testPingNetwork 即可解决这个问题。

好的，明白了，谢谢，注释掉重跑一下就行了
