### ISSUE TITLE
xcode 14 build failed

### ISSUE THREAD

**Issue by wenyuanyuan** [bytedance/Fastbot_iOS#103]
error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by geron-cn** [comment]
try replace `XCTAutomationSupport.framework ` with a lower version framework.  backup your framework first.
xcode13.0:
[XCTAutomationSupport.framework.zip](https://github.com/bytedance/Fastbot_iOS/files/9604829/XCTAutomationSupport.framework.zip)

**Comment by Edwick-Raj** [comment]
@geron-cn Hey, do u have the XCTAutomationSupport.framework  with lower version for **tvos**?

**Comment by geron-cn** [comment]
> @geron-cn Hey, do u have the XCTAutomationSupport.framework with lower version for **tvos**?

here is xcode13.0 tvos framework: 
[XCTAutomationSupport.framework.tvos.zip](https://github.com/bytedance/Fastbot_iOS/files/9623783/XCTAutomationSupport.framework.tvos.zip)

**Comment by Pycoder0901** [comment]
error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by PureWhiteo** [comment]
hihi, could you tell me how to replace XCTAutomationSupport.framework with a lower version framework?

**Comment by nicole1010** [comment]
> 
您好，您这个xcode13的XCTAutomationSupport.framework.zip，解压后长这样——
![image](https://user-images.githubusercontent.com/8278856/201628516-766e1d47-18b2-427a-823a-c23171fcd8cd.png)

正常的XCTAutomationSupport.framework看起来是文件夹。
请问是不是我解压的不对？

**Comment by qingtianwaa** [comment]
> > 
> 
> 您好，您这个xcode13的XCTAutomationSupport.framework.zip，解压后长这样—— ![image](https://user-images.githubusercontent.com/8278856/201628516-766e1d47-18b2-427a-823a-c23171fcd8cd.png)
> 
> 正常的XCTAutomationSupport.framework看起来是文件夹。 请问是不是我解压的不对？
 
右击XCode展开包内容，一层层找到对应的XCTAutomationSupport.framework，然后复制并替换到XCode14对应的路径下就好了，我昨天也是这么做的。但是记得把XCode14原来的XCTAutomationSupport.framework 备份下。

**Comment by nicole1010** [comment]
> 

您好，我这是下载zip包解压后文件显示成 xcode.  内容好像不对？应该是一个.framework。
请问您那边解压后显示的是啥？

**Comment by geron-cn** [comment]
更新到最新版本，重新执行 pod install 。
