### ISSUE TITLE
没人修一下吗？？？

### ISSUE THREAD

**Issue by Pycoder0901** [bytedance/Fastbot_iOS#106]
error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by MichaelShuai** [comment]
在build setting里将Exclude Arch. i386改为arm64

**Comment by geron-cn** [comment]
更新到最新代码，重新执行 pod install。
