### ISSUE TITLE
run test时，运行一段时间后，线程被kill

### ISSUE THREAD

**Issue by wangshaoce** [bytedance/Fastbot_iOS#11]
xcode log：[fastbot] : build state cost: 0.000s action cost: 0.000s total cost 0.000s
2021-08-04 05:14:08.915766+0800 FastbotRunner-Runner[696:369904] ticker shot desc cost 0.059585  netact  0.000556 second, left 18108.826298s
    t = 25099.91s Open com.bilibili.bilianime
    t = 25100.01s     Activate com.bilibili.bilianime
/Users/wangshaoce/bilibili_test/Fastbot_iOS/Fastbot-iOS/FastbotRunner/FastbotRunner.m:73: error: -[FastbotRunner testFastbot] : Failed to launch com.bilibili.bilianime: 未能完成该操作。Unable to launch com.bilibili.bilianime because the device was not, or could not be, unlocked.
/Users/wangshaoce/bilibili_test/Fastbot_iOS/Fastbot-iOS/FastbotRunner/FastbotRunner.m:73: error: -[FastbotRunner testFastbot] : Failed to activate application 'com.bilibili.bilianime' (current state: Running Background Suspended)
    t = 25160.18s         Wait for com.bilibili.bilianime to idle
    t = 25161.29s Tear Down
2021-08-04 05:15:16.453698+0800 FastbotRunner-Runner[696:178321] state g0s5590 action SCROLL_TOP_DOWN pos[4,19,410,70] throttle 0.10
Test Case '-[FastbotRunner testFastbot]' failed (25166.559 seconds).
Test Suite 'FastbotRunner' failed at 2021-08-04 05:15:16.560.
	 Executed 1 test, with 2 failures (0 unexpected) in 25166.559 (25166.560) seconds
Test Suite 'FastbotRunner.xctest' failed at 2021-08-04 05:15:16.563.
	 Executed 1 test, with 2 failures (0 unexpected) in 25166.559 (25166.563) seconds
Test Suite 'Selected tests' failed at 2021-08-04 05:15:16.572.
	 Executed 1 test, with 2 failures (0 unexpected) in 25166.559 (25166.573) seconds
[fastbot] : select new action from unvisited Unsaturated
[fastbot] : total visit count is 52568
[fastbot] : state visited: 3 
[fastbot] : action first visited, get reward 1.000000
[fastbot] : got reward: 18.1485
[fastbot] : build state cost: 0.000s action cost: 0.000s total cost 0.000s
2021-08-04 05:15:18.738365+0800 FastbotRunner-Runner[696:178321] state g0s3586 action SCROLL_RIGHT_LEFT pos[2,2,410,926] throttle 0.10
FastbotRunner-Runner(696,0x16d197000) malloc: *** error for object 0x2825de390: pointer being freed was not allocated
FastbotRunner-Runner(696,0x16d197000) malloc: *** set a breakpoint in malloc_error_break to debug
(lldb) 

启动命令：
![image](https://user-images.githubusercontent.com/27803057/128116328-e256522a-4ede-4072-9c7a-a7aa1be301af.png)

**Comment by wangshaoce** [comment]
![image](https://user-images.githubusercontent.com/27803057/128116376-590b4c89-ac53-426c-8b0a-b825799a7a63.png)

**Comment by geron-cn** [comment]
第一个错：`Failed to launch com.bilibili.bilianime: 未能完成该操作。Unable to launch com.bilibili.bilianime because the device was not, or could not be, unlocked. ` 需要检查下 包名是否正确， app 是否可以正常运行（是否被信任）

第二问题： 话说你这是个后台进程或者是启动时卡死无法拉到前台么？ 需要捞取一下 crash  分析下这个问题哈，捞取方式参考： #2 ， 然后指针错误这个问题看下这个crash我再进一步分析吧

**Comment by wangshaoce** [comment]
第一个错：包名正确。app可以正常运行，但是有一个业务面板白屏。
第二个问题：无crash

**Comment by geron-cn** [comment]
这边看了下， 这个截图的中基地址好像不太对， 麻烦提供捞一下  FastbotRunner 的crash文件， 用xcode 导出 ips 即可。

**Comment by lrfighting** [comment]
> Failed

请问第一个问题最后怎么解决的？
