### ISSUE TITLE
运行出现报错无法截图

### ISSUE THREAD

**Issue by Jerrywang77** [bytedance/Fastbot_iOS#12]
2021-08-04 13:40:41.317466+0800 FastbotRunner-Runner[447:28160] get desc failed 0
    t =   478.07s Pressing Home button
    t =   480.18s Open com.ihoment.GoVeeSensor
    t =   480.18s     Activate com.ihoment.GoVeeSensor
    t =   480.19s         Wait for com.ihoment.GoVeeSensor to idle
**<unknown>:0: error: -[FastbotRunner testFastbot] : Failed to get screenshot: Timed out while requesting screenshot.**
    t =   481.21s Tear Down
Test Case '-[FastbotRunner testFastbot]' failed (484.085 seconds).

**Comment by geron-cn** [comment]
看下是否必现， 可参照 readme 中的 Q&A， 如果必现， 麻烦提供下 运行环境（iphone/iOS/XCode/OSX版本），被测 App 截图

**Comment by Jerrywang77** [comment]
出现概率较高，运行了3次出现两次，第一次在APP弹窗页面停留一会出现，第二次出现APP被退到后台，不确定哪个场景出现

**Comment by Jerrywang77** [comment]
![image](https://user-images.githubusercontent.com/41882120/128132100-ef687df6-d96a-4a20-9db9-bd2afbe80fa9.png)
iOS 14.4
![image](https://user-images.githubusercontent.com/41882120/128132247-2b1641e2-ca58-48e9-8ea5-1b496ffeaa35.png)

**Comment by geron-cn** [comment]
related： #16
