### ISSUE TITLE
你的二进制文件不是XCTAutomationSupport for architecture arm64的允许客户端

### ISSUE THREAD

**Issue by Kim-LL** [bytedance/Fastbot_iOS#120]
Xcode: 14.2
苹果设备: 16.3.1
运行 testPingNetwork 报错，错误内容:
Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by geron-cn** [comment]
更新到最新版本，  重新执行 pod install
