### ISSUE TITLE
运行一会后被终止

### ISSUE THREAD

**Issue by Jerrywang77** [bytedance/Fastbot_iOS#13]
![image](https://user-images.githubusercontent.com/41882120/128128850-e26da86f-d73e-4228-96e0-b4c4a0856dec.png)

**Comment by geron-cn** [comment]
必现的么？ 可参照下 readme 中的 Q&A， 如果还出现的话， 麻烦提供下启动参数/命令和app截图

**Comment by Jerrywang77** [comment]
不是必现，运行到弹窗页面后一直没有跳出去，等了会就出现了

**Comment by Jerrywang77** [comment]
![image](https://user-images.githubusercontent.com/41882120/128131055-a02929a2-c4d8-4685-8c3f-83203915e428.png)

**Comment by geron-cn** [comment]
related： #16
