### ISSUE TITLE
使用命令行运行，duration等参数未生效

### ISSUE THREAD

**Issue by CYsuncheng** [bytedance/Fastbot_iOS#15]
命令：BUNDLEID=com.xxx duration=30 throttle=300 xcodebuild test  -workspace Fastbot-iOS.xcworkspace -scheme FastbotRunner  -configuration Release  -destination 'platform=iOS,id=00008101-xx' -only-testing:FastbotRunner/FastbotRunner/testFastbot

运行时，duration是30分钟，但是实际运行是5分钟，后来发现，我在xcode里面配置的scheme是5分钟，这个命令行参数未生效

**Comment by geron-cn** [comment]
参照 readme 中这句话哈：` if IDE scheme Env Vars changed , command Env Var would be void`

你需要回退下 xcode scheme 的配置， 使得 xcode 使用环境变量的值做实际参数。

**Comment by CYsuncheng** [comment]
@geron-cn ok，明白了
