### ISSUE TITLE
运行报错，APP卡住

### ISSUE THREAD

**Issue by Jerrywang77** [bytedance/Fastbot_iOS#16]
![image](https://user-images.githubusercontent.com/41882120/128138057-d781ef5c-4a8e-445c-a1ce-39c1ff71a46e.png)

运行4次出现一次，xcode：Version 12.5.1 (12E507)、Mac os：11.4、iOS：14.4

APP页面截图：
![image](https://user-images.githubusercontent.com/41882120/128138396-0b8f45e6-0296-416c-a9d1-b2f1b1a23822.png)

**Comment by geron-cn** [comment]
可参考 readme 中的 Q&A， IPCTimeout 一般归因未连接不稳定， 可以 重启工具/重启手机/更换 USB 线等 然后重试。
