### ISSUE TITLE
无法安装（通过升级xocde以及重新拉取项目，可以正常使用了）

### ISSUE THREAD

**Issue by ouhehuang** [bytedance/Fastbot_iOS#18]
Details

Unable to install "FastbotRunner-Runner"
Domain: com.apple.dtdevicekit
Code: -402620415
--
App installation failed
Domain: com.apple.dtdevicekit
Code: -402620415
Failure Reason: An unknown error has occurred.
User Info: {
    DVTRadarComponentKey = 487927;
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x00000001250566e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000125056de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x000000012509656a __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 164
	3   DVTFoundation                       0x000000010b16b156 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000125096301 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1589
	5   IDEiOSSupportCore                   0x0000000124f2fa25 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4523
	6   DVTFoundation                       0x000000010b29c3ba __DVT_CALLING_CLIENT_BLOCK__ + 7
	7   DVTFoundation                       0x000000010b29da92 __DVTDispatchAsync_block_invoke + 809
	8   libdispatch.dylib                   0x00007fff796a85f8 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00007fff796a963d _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00007fff796af8e0 _dispatch_lane_serial_drain + 602
	11  libdispatch.dylib                   0x00007fff796b0396 _dispatch_lane_invoke + 385
	12  libdispatch.dylib                   0x00007fff796b86ed _dispatch_workloop_worker_thread + 598
	13  libsystem_pthread.dylib             0x00007fff798e3611 _pthread_wqthread + 421
	14  libsystem_pthread.dylib             0x00007fff798e33fd start_wqthread + 13
);
}
--

**Comment by geron-cn** [comment]
参照这个  https://developer.apple.com/forums/thread/126326
可尝试 更换usb线/ 更换账号/ 升级xcode / 卸载所有 inhouse/个人 证书app 等

**Comment by geron-cn** [comment]
udpate：  查看手机系统时间是否自动更新

**Comment by ouhehuang** [comment]
通过升级xocde以及重新拉取项目，可以正常使用了
