### ISSUE TITLE
运行时间结束时报错

### ISSUE THREAD

**Issue by Jerrywang77** [bytedance/Fastbot_iOS#21]
![image](https://user-images.githubusercontent.com/41882120/128286415-242b61a1-2abb-4062-9a8e-59ddb9b1d096.png)

**Comment by geron-cn** [comment]
同学，你这边这几个 issue 都集中在。IPCTimeout 这，可参考 readme 中的 Q&A， IPCTimeout 一般归因为连接不稳定， 可以 重启工具/重启手机/更换 USB 线等 然后重试。 
> related： #16
