### ISSUE TITLE
testFastbot执行报错“Failed to find flow 102c14c78”

### ISSUE THREAD

**Issue by ShenJiaojiao** [bytedance/Fastbot_iOS#23]
![image](https://user-images.githubusercontent.com/21237513/128327002-0433f655-23c7-448b-8313-7ed511f4511f.png)
但是在执行testPingNetwork时候已经提示网络success了
![image](https://user-images.githubusercontent.com/21237513/128327254-5e7b937d-7982-4027-bb53-5aecf50501e9.png)
参数配置应该都是对的
![image](https://user-images.githubusercontent.com/21237513/128327427-c1ec4938-4d7b-425c-b018-4770c4ae65b7.png)

**Comment by ShenJiaojiao** [comment]
![image](https://user-images.githubusercontent.com/21237513/128328846-1d1dc280-7c29-4927-a24b-89a978a8499c.png)

**Comment by geron-cn** [comment]
你这个报错在后面： `Failed to launch com.apple.Pages ！`
意思你本地没有这个 被测试App， 你需要按照 readme， 指定正确的被测试的 App 的 BUNDLEID
