### ISSUE TITLE
可以同时起来俩吗，跑俩设备

### ISSUE THREAD

**Issue by wenyuanyuan** [bytedance/Fastbot_iOS#29]

**Comment by geron-cn** [comment]
可以， xcode IDE 或 命令 或者 tidevice 都可以的， 具体设备上限取决于设备性能。
wechat 交流群中有同学 一台 win 使用 tidevice 带 15台设备运行。

**Comment by superWenshuo** [comment]
@wenyuanyuan  能给个xcode的实例命令吗？没看到有方案

**Comment by geron-cn** [comment]
﻿可以的同时多设备的， 命令行启动方式英文手册也有示例

发自我的iPhone
