### ISSUE TITLE
pod install --repo-update 失败

### ISSUE THREAD

**Issue by heyalu007** [bytedance/Fastbot_iOS#3]
---------------------------------------------
Error loading the plugin `cocoapods-byted-dependency-1.2.47`.

NameError - uninitialized constant Informative
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-byted-dependency-1.2.47/lib/byted-dependency.rb:14:in `compatibility_check'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-byted-dependency-1.2.47/lib/byted-dependency.rb:46:in `<top (required)>'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-byted-dependency-1.2.47/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `block in safe_activate_and_require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `each'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
---------------------------------------------

---------------------------------------------
Error loading the plugin `cocoapods-mbox-support-1.6.0.5`.

Gem::ConflictError - Unable to activate cocoapods-mbox-support-1.6.0.5, because cocoapods-1.10.1 conflicts with cocoapods (< 1.7.0)
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:2298:in `raise_if_conflicts'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1415:in `activate'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
---------------------------------------------

### Command

```
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod install --repo-update
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.4 (12D4e)
         Git : git version 2.27.0
Ruby lib dir : /Users/heyalu/.rvm/rubies/ruby-2.6.3/lib
Repositories : ***
```

### Error

```
NameError - uninitialized constant Informative
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-byted-dependency-1.2.47/lib/byted-dependency.rb:14:in `compatibility_check'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-byted-dependency-1.2.47/lib/byted-dependency.rb:29:in `parse'
/Users/heyalu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/heyalu/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/heyalu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by geron-cn** [comment]
参照 readme 中 Q&A，执行： sudo gem install cocoapods -v=1.8.1
另外： cocoapods 各种冲突， 建议使用 bundle 来管理 gem 版本；
