### ISSUE TITLE
test的时候testfastbot失败

### ISSUE THREAD

**Issue by luxusheng** [bytedance/Fastbot_iOS#31]
![image](https://user-images.githubusercontent.com/75831124/129006175-6a07afbf-6771-4d77-a563-2e1d254ff07b.png)

**Comment by ShenJiaojiao** [comment]
这个我遇见过，你可以看下具体日志信息，看看是不是包名配置错了

**Comment by luxusheng** [comment]
> 这个我见过，你可以看下具体日志信息，看看是不是包名配置错了

  Assertions: Assertion Failure: Failed to launch com.apple.Pages: 未能完成该操作。Application info provider (FBSApplicationLibrary) returned nil for "com.apple.Pages" 
可是我bundle配置了唯一啊

**Comment by ShenJiaojiao** [comment]
> > 这个我见过，你可以看下具体日志信息，看看是不是包名配置错了
> 
> Assertions: Assertion Failure: Failed to launch com.apple.Pages: 未能完成该操作。Application info provider (FBSApplicationLibrary) returned nil for "com.apple.Pages"
> 可是我bundle配置了唯一啊

com.apple.Pages这个是默认的包名，显然你没有修改这个包名为你自己的包名。。
![image](https://user-images.githubusercontent.com/21237513/129146450-e08050b7-f499-4060-ad2d-42477f8828d8.png)
