### ISSUE TITLE
放到Jenkins上执行报错

### ISSUE THREAD

**Issue by wenyuanyuan** [bytedance/Fastbot_iOS#37]
![image](https://user-images.githubusercontent.com/14310258/130220943-05e4980d-51b9-47f7-a911-b850e02dc08c.png)
    /usr/bin/codesign --force --sign 4D2F77F076A50438CE3E071A1042C5090B2540FB --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/mobileqa/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ftlwwegzexsvdhdubsndhwljhbbo/Build/Products/Release-iphoneos/FastbotRunner-Runner.app/Frameworks/libXCTestSwiftSupport.dylib
/Users/mobileqa/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ftlwwegzexsvdhdubsndhwljhbbo/Build/Products/Release-iphoneos/FastbotRunner-Runner.app/Frameworks/libXCTestSwiftSupport.dylib: replacing existing signature
/Users/mobileqa/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ftlwwegzexsvdhdubsndhwljhbbo/Build/Products/Release-iphoneos/FastbotRunner-Runner.app/Frameworks/libXCTestSwiftSupport.dylib: errSecInternalComponent
Command /usr/bin/codesign failed with exit code 1

Test session results, code coverage, and logs:
	/Users/mobileqa/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ftlwwegzexsvdhdubsndhwljhbbo/Logs/Test/Test-FastbotRunner-2021.08.20_18-27-25-+0800.xcresult

Testing failed:
	FastbotRunner:
		Command /usr/bin/codesign failed with exit code 1
	Testing cancelled because the build failed.

** TEST FAILED **

The following build commands failed:
	CodeSign /Users/mobileqa/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ftlwwegzexsvdhdubsndhwljhbbo/Build/Products/Release-iphoneos/FastbotRunner-Runner.app/Frameworks/libXCTestSwiftSupport.dylib
(1 failure)
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by geron-cn** [comment]
签名问题， 看下https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen

**Comment by geron-cn** [comment]
另外建议可以使用 test-without-build 命令
