### ISSUE TITLE
运行起来之后，执行了一次页面滑动，就test  failed是什么情况

### ISSUE THREAD

**Issue by zhangshixue965** [bytedance/Fastbot_iOS#39]
同标题，运行一会就test failed，求大佬解答～～
![image](https://user-images.githubusercontent.com/69798228/130545755-041a24ad-169f-44f4-a3a4-9496132982d6.png)

**Comment by geron-cn** [comment]
看起来这个截图里面没有相关的错误信息， 麻烦贴下更详细的 log 和启动参数， 另外尝试多次启动都是这个错误吗？

**Comment by zhangshixue965** [comment]
> 看起来这个截图里面没有相关的错误信息， 麻烦贴下更详细的 log 和启动参数， 另外尝试多次启动都是这个错误吗？

手机更新14系统之后可以正常运行了，之前是ios11系统，可能对11系统兼容不是很好

**Comment by geron-cn** [comment]
> 1系统，可能对11系统兼容不是很好

11 的兼容从我们拿到的所有测试数据看应该是没有问题的， 之前有遇到过 如果你的 DeviceSupport 重的 dmg 如果是下载的（非xcode自带），有可能触发这种问题
