### ISSUE TITLE
执行pod install --repo-update失败

### ISSUE THREAD

**Issue by xumeng20102722** [bytedance/Fastbot_iOS#4]
zsh: command not found: pod

**Comment by geron-cn** [comment]
releted https://github.com/bytedance/Fastbot_iOS/issues/3

**Comment by ch3265936** [comment]
sudo gem install cocoapods -v=1.8.1

**Comment by sadmenmen** [comment]
Fastbot 目录下还有一个Fastbot ，你们应该是没进去第二个目录把，文档里面写了先进第一个Fastbot 目录，然后再进第二个Fastbot ，然后再输入命令
