### ISSUE TITLE
stub模式怎么注入进测试包呢

### ISSUE THREAD

**Issue by ShenJiaojiao** [bytedance/Fastbot_iOS#44]
ios小白，第一次弄，不太明白要怎么把stub模式注入呢
![image](https://user-images.githubusercontent.com/21237513/131815170-e503a854-5d4c-4f4e-a90a-ca43e6963408.png)
target选中stub吗？

**Comment by geron-cn** [comment]
编译 fastbot_stub 完成之后， 使用 https://github.com/KJCracks/yololib  注入被测试 APP中， 具体方法 google yololib 即可

**Comment by ShenJiaojiao** [comment]
> 编译 fastbot_stub 完成之后， 使用 https://github.com/KJCracks/yololib 注入被测试 APP中， 具体方法 google yololib 即可
================》
怎么设置登陆账号呢？给个方向，谢谢哦

**Comment by geron-cn** [comment]
> > 编译 fastbot_stub 完成之后， 使用 https://github.com/KJCracks/yololib 注入被测试 APP中， 具体方法 google yololib 即可
> > ================》
> > 怎么设置登陆账号呢？给个方向，谢谢哦

可以参考  #28
