### ISSUE TITLE
iOS monkey目前支持二次开发吗？

### ISSUE THREAD

**Issue by yayyds** [bytedance/Fastbot_iOS#47]
如果支持，目前有哪些功能支持二次开发？有相关文档吗

**Comment by geron-cn** [comment]
理论基础可以参考这篇文章：***More detail see at [Fastbot architecture](https://mp.weixin.qq.com/s/QhzqBFZygkIS6C69__smyQ)
扩展的手册 可参考英文手册的： Advanced Extension 部分
