### ISSUE TITLE
看了下源码，看不到里面大神们的一些具体实现，后续有打算开放么

### ISSUE THREAD

**Issue by Maxxxx24** [bytedance/Fastbot_iOS#5]

**Comment by Maxdong24** [comment]
看了下源码，看不到里面大神们的一些具体实现，后续有打算开放么

**Comment by geron-cn** [comment]
https://mp.weixin.qq.com/s/QhzqBFZygkIS6C69__smyQ
同学可以先看这个文章哈， 里面有具体的技术原理和方案。

**Comment by Maxdong24** [comment]
> https://mp.weixin.qq.com/s/QhzqBFZygkIS6C69__smyQ
> 同学可以先看这个文章哈， 里面有具体的技术原理和方案。

大佬 想问下这个launchenv这个参数用来做什么的？另外log里面有
TESTED VC IS:

TESTED VC Count: 0
---------
TOTAL VS IS:

TOTAL VC COUNT:0
viewcontroller页面统计这个数据怎么来的？



<br class="Apple-interchange-newline">

**Comment by Maxdong24** [comment]
另外一些定制化的Schema 跳转、屏蔽设置等  如何在代码中做设置？@geron-cn

**Comment by geron-cn** [comment]
这些是会在 stub 模式下会被采集的；
制化的Schema 跳转、屏蔽设置等暂时未集成， 目前需要自己在 stub 中去扩展这部分代码。

**Comment by geron-cn** [comment]
launchenv 是传递给被测试App 的启动环境变量， 可参照 readme 说明， 一般被测试App没啥需求的话不设置就好

**Comment by Maxxxx24** [comment]
> launchenv 是传递给被测试App 的启动环境变量， 可参照 readme 说明， 一般被测试App没啥需求的话不设置就好

好滴 谢谢~
