### ISSUE TITLE
执行testPingNetwork报错，麻烦看下。

### ISSUE THREAD

**Issue by pxrgod** [bytedance/Fastbot_iOS#50]
Ld /Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Products/Debug-iphoneos/FastbotRunner-Runner.app/PlugIns/FastbotRunner.xctest/FastbotRunner normal (in target 'FastbotRunner' from project 'Fastbot-iOS')
    cd /Users/hspcadmin/Desktop/Fastbot_iOS/Fastbot-iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios9.0 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Products/Debug-iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F/Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/Users/hspcadmin/Desktop/Fastbot_iOS/Fastbot-iOS/Pods/../fastbot -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/Developer/Library/Frameworks -filelist /Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Intermediates.noindex/Fastbot-iOS.build/Debug-iphoneos/FastbotRunner.build/Objects-normal/arm64/FastbotRunner.LinkFileList -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Intermediates.noindex/Fastbot-iOS.build/Debug-iphoneos/FastbotRunner.build/Objects-normal/arm64/FastbotRunner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lxml2.2 -framework FastbotLib -framework XCTAutomationSupport -framework XCTest -framework fastbot_cv -framework fastbot_native -framework XCTest -lPods-FastbotRunner -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Intermediates.noindex/Fastbot-iOS.build/Debug-iphoneos/FastbotRunner.build/Objects-normal/arm64/FastbotRunner_dependency_info.dat -o /Users/hspcadmin/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ecjlnosjaifznhcycjsrnhjqvewf/Build/Products/Debug-iphoneos/FastbotRunner-Runner.app/PlugIns/FastbotRunner.xctest/FastbotRunner

ld: library not found for -lPods-FastbotRunner

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by geron-cn** [comment]
使用的是 Fastbot-iOS.xcworkspace 么？

**Comment by pxrgod** [comment]
使用的是xccodeproj文件打开进行执行的发自我的华为手机-------- 原始邮件 --------发件人： gero ***@***.***>日期： 2021年9月14日周二 傍晚5:34收件人： bytedance/Fastbot_iOS ***@***.***>抄送： pxrgod ***@***.***>, Author ***@***.***>主    题： Re: [bytedance/Fastbot_iOS] 执行testPingNetwork报错，麻烦看下。 (#50)

使用的是 Fastbot-iOS.xcworkspace 么？

**Comment by geron-cn** [comment]
> 使用的是xccodeproj文件打开进行执行的发自我的华为手机-------- 原始邮件 --------发件人： gero ***@***.***>日期： 2021年9月14日周二 傍晚5:34收件人： bytedance/Fastbot_iOS ***@***.***>抄送： pxrgod ***@***.***>, Author ***@***.***>主 题： Re: [bytedance/Fastbot_iOS] 执行testPingNetwork报错，麻烦看下。 (#50) 使用的是 Fastbot-iOS.xcworkspace 么？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

关闭 xcodeproject， 使用 xcworkspace 即可解决该问题

**Comment by pxrgod** [comment]
多谢回复，早上再次安装的时候，出现了这个异常，说是有个库应该没有依赖上
dyld: dyld cache load error: syscall to map cache into shared region failed
dyld: Library not loaded: /System/Library/Frameworks/UIKit.framework/UIKit
  Referenced from: /private/var/containers/Bundle/Application/2926D988-AE83-4F1A-AB07-89FB43CD4191/FastbotRunner-Runner.app/FastbotRunner-Runner
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib
(lldb)

**Comment by pxrgod** [comment]
> 多谢回复，早上再次安装的时候，出现了这个异常，说是有个库应该没有依赖上
> dyld: dyld cache load error: syscall to map cache into shared region failed
> dyld: Library not loaded: /System/Library/Frameworks/UIKit.framework/UIKit
> Referenced from: /private/var/containers/Bundle/Application/2926D988-AE83-4F1A-AB07-89FB43CD4191/FastbotRunner-Runner.app/FastbotRunner-Runner
> Reason: image not found
> dyld: launch, loading dependent libraries
> DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib
> (lldb)

这个是我本机环境的问题，不是问题
