### ISSUE TITLE
ios monkey命令行运行支持传入多设备吗

### ISSUE THREAD

**Issue by yayyds** [bytedance/Fastbot_iOS#54]
您好，想请问下，iOS端命令行支持输入多个设备跑吗？
iOS执行monkey完成后，会收集anr信息吗？

**Comment by geron-cn** [comment]
xcodebuild without-build 本身是支持多设备的， 使用 tidevice 多次执行命令可以达到同样的效果。

异常信息收集这块工具本身暂未集成， 通常依赖 app 本身集成的sdk来完成（例如 bugly等），或可用 xcode导出 crash等相关信息。
