### ISSUE TITLE
急急急 iOS15是否能支持

### ISSUE THREAD

**Issue by wenyuanyuan** [bytedance/Fastbot_iOS#57]

**Comment by geron-cn** [comment]
iOS15 是直接支持的

**Comment by wenyuanyuan** [comment]
> iOS15 是直接支持的
为啥一跑iOS15，刚跑起来就失败啊
Showing Recent Messages
: Failed to get screenshot: Legacy screen requests are no longer supported

**Comment by wenyuanyuan** [comment]
![wecom-temp-c30c592d8c0f35353587ddb937aa07e5](https://user-images.githubusercontent.com/14310258/135017541-68374ce1-fec2-4694-a960-97efe44060bb.png)

**Comment by 554632107** [comment]
![image](https://user-images.githubusercontent.com/54433466/147305786-bf096c16-dd26-474a-ba8c-4dead945d5c9.png)
![image](https://user-images.githubusercontent.com/54433466/147305812-5a4af749-cdc4-4ec9-849a-da55a669276c.png)
