### ISSUE TITLE
library not found for -lPods-FastbotRunner

### ISSUE THREAD

**Issue by ch3265936** [bytedance/Fastbot_iOS#6]
sudo gem install cocoapods [--pre](url)
之后编译通过，但是test执行报错“library not found for -lPods-FastbotRunner”

**Comment by geron-cn** [comment]
确认下这两步执行过没， 参照 readme：
`cd Fastbot-iOS && pod install --repo-update`
`Open Fastbot-iOS.xcworkspace`  使用的工程是 xcworkspace

**Comment by ch3265936** [comment]
感谢
