### ISSUE TITLE
打开FastbotRunner 网络权限：在执行pingTestNetwork之后，在手机点击FastbotRunner-Runner App，闪退

### ISSUE THREAD

**Issue by Sherryutan** [bytedance/Fastbot_iOS#64]
"4.打开 FastbotRunner 网络权限： 执行 pingTestNetwork（此处可参照步骤3-2），此时在手机上点击 FastbotRunner-Runner App，弹出黑色界面后，等待 30s 左右，点击 Home 键（或屏幕底部上滑）回到桌面，此时弹出是否打开网络权限的弹窗，选择无线网络或蜂窝网即可。直到 Xcode 运行 log 中出现 ping network success 则打开网络成功，如果不成功可尝试重复步骤4"

执行 pingTestNetwork之后，在手机点击FastbotRunner-Runner App，闪退

**Comment by geron-cn** [comment]
> related: #59

**Comment by zys520** [comment]
> "4.打开 FastbotRunner 网络权限： 执行 pingTestNetwork（此处可参照步骤3-2），此时在手机上点击 FastbotRunner-Runner App，弹出黑色界面后，等待 30s 左右，点击 Home 键（或屏幕底部上滑）回到桌面，此时弹出是否打开网络权限的弹窗，选择无线网络或蜂窝网即可。直到 Xcode 运行 log 中出现 ping network success 则打开网络成功，如果不成功可尝试重复步骤4"
> 
> 执行 pingTestNetwork之后，在手机点击FastbotRunner-Runner App，闪退
