### ISSUE TITLE
图像处理的badcase

### ISSUE THREAD

**Issue by WenXiaoHui001** [bytedance/Fastbot_iOS#66]
跑Fastbot_ios时候，如果出现页面只有截图中的情况时，会一直点新增地址跳到下级页面操作之后再返回该页面，无法跳出去
![8 6Y_D`KAXM$X$Z@3353_AF](https://user-images.githubusercontent.com/70584623/141885106-bffe6613-fd1b-4a15-a9ef-e1c329e223b7.jpg)

**Comment by geron-cn** [comment]
麻烦提供一张屏幕截图

**Comment by WenXiaoHui001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/Fastbot_iOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/Fastbot_iOS] 图像处理的badcase (Issue #66)





 
麻烦提供一张屏幕截图
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WenXiaoHui001** [comment]
> 麻烦提供一张屏幕截图
