### ISSUE TITLE
使用crontab在mac上跑shell脚本，异常如下No signing certificate "iOS Development" found: No "iOS Developm

### ISSUE THREAD

**Issue by superWenshuo** [bytedance/Fastbot_iOS#69]
异常如下，但是我直接运行shell脚本是可以成功的。

Create build description
Build description signature: dbdcfc680e6eca3e7ec36608c066c529
Build description path: /var/root/Library/Developer/Xcode/DerivedData/Fastbot-iOS-ehsnztwpxhszwfaqwjkgmqaqvtbw/Build/Intermediates.noindex/XCBuildData/dbdcfc680e6eca3e7ec36608c066c529-desc.xcbuild

note: Build preparation complete
note: Building targets in parallel
error: No profiles for 'xx.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'xx.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'FastbotRunner' from project 'Fastbot-iOS')

shell如下：
#!/bin/bash

cd /Users/xxx/git/Fastbot_iOS/Fastbot-iOS&&
BUNDLEID=com.sohu.inhouse.iphonevideo duration=1 throttle=100 xcodebuild test  -workspace Fastbot-iOS.xcworkspace -scheme FastbotRunner  -configuration Release  -destination 'platform=iOS,id=f634c33ea8bd0e5fdf89f3801f86579c68958fa9' -only-testing:FastbotRunner/FastbotRunner/testFastbot

**Comment by geron-cn** [comment]
Apple证书相关问题，参考苹果官方文档修改项目或Xcode配置或Apple ID相关设置

发自我的iPhone

**Comment by superWenshuo** [comment]
@geron-cn  我感觉也是和证书相关，但是同一个shell手动执行没问题，也是醉了

**Comment by superWenshuo** [comment]
已经解决crontab任务找不到build的证书，使用launchctl 多个sh脚本+多个设备能正常执行
