### ISSUE TITLE
通过命令行传递参数给xcodebuild失败

### ISSUE THREAD

**Issue by supergithuber** [bytedance/Fastbot_iOS#93]
我使用文档：https://github.com/bytedance/Fastbot_iOS/blob/main/Doc/handbook-cn.md
提到的通过命令行传递参数的方式：BUNDLEID=xxx duration=240 throttle=300 xcodebuild test -workspace Fastbot-iOS.xcworkspace -scheme FastbotRunner -configuration Release -destination 'platform=iOS,id=00008030-001804563E44802E' -only-testing:FastbotRunner/FastbotRunner/testFastbot

在测试代码中打印环境变量，并没有BUNDLEID、duration、throttle
并且使用的bundleid依然是默认的com.apple.Pages

**Comment by geron-cn** [comment]
使用命令行则不能手动更改 xcode 的 scheme设置。
![image](https://user-images.githubusercontent.com/1511316/177687152-2ec19d1c-4784-45bb-aa7a-9f5df68400ce.png)
