### ISSUE TITLE
ios 15.5运行testFastbot，运行失败Failed to get screenshot: Legacy screen requests are no longer supported

### ISSUE THREAD

**Issue by chenweiwei** [bytedance/Fastbot_iOS#95]
![image](https://user-images.githubusercontent.com/4162920/177266030-04d55810-5de8-4fac-922a-ee35942c9505.png)

ios 15.5 运行testFastbot，运行失败Failed to get screenshot: Legacy screen requests are no longer supported 
相同的问题
https://github.com/bytedance/Fastbot_iOS/issues/72

**Comment by geron-cn** [comment]
参考： https://discuss.appium.io/t/unable-to-take-screen-shot-for-ios-15-1/35333/2
update Xcode to 13
